services:
  - type: web
    name: customer-support-api
    runtime: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: customer-support-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: customer-support-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: customer-support-db
          property: dbname
      - key: DB_USER
        fromDatabase:
          name: customer-support-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: customer-support-db
          property: password
      - key: SENDGRID_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://chat-bot-5gvuq3vu7-atharvasable1204-gmailcoms-projects.vercel.app
      - key: ALLOWED_ORIGINS
        value: http://localhost:3000,http://localhost:5173,https://chat-bot-5gvuq3vu7-atharvasable1204-gmailcoms-projects.vercel.app

databases:
  - name: customer-support-db
    plan: free
